# Generated by Django 3.2.12 on 2022-03-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='sender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='thread_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
